project_name: Corgi

builds:
  - id: "corgi"
    main: ./cmd/corgi/main.go

    # Disable CGO
    env: [CGO_ENABLED=0]

    # Build for most SO and arch.
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
