version: '3.5'
services:
  server:
    image: server
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=local
      - APP_DSN=postgres://db/corgi?sslmode=disable&user=postgres&password=postgres
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "go_restful"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
