version: '3.5'
services:
  app:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=local
      - APP_DSN=postgres://db/corgi?sslmode=disable&user=postgres&password=postgres
    depends_on:
      - db
      - broker

  db:
    image: "cockroachdb/cockroach:v21.2.3"
    command: start-single-node --insecure
    restart: always
    ports:
      - "26257:26257"
      - "8080:8080"

  db-init:
    image: "cockroachdb/cockroach:v21.2.3"
    command: sql --insecure --host="db:26257" --execute="CREATE DATABASE IF NOT EXISTS corgi"
    depends_on:
      - db

  broker:
    image: "nats:2.7.1"
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
      #- "6222:6222" # is a routing port for clustering.
