basePath: /
definitions:
  app.PostURL:
    properties:
      keyword:
        example: google
        type: string
      title:
        example: Google Home
        type: string
      url:
        example: https://www.google.com
        type: string
    type: object
  app.URL:
    properties:
      active:
        example: false
        type: boolean
      created_at:
        example: "2021-10-18T00:45:07.818344164-03:00"
        type: string
      id:
        example: eed7df28-5a16-46f0-b5bf-c26071a42ade
        type: string
      keyword:
        example: google
        type: string
      owner_id:
        example: 5ca04a43-ff3c-4154-a8ad-02e2e906a847
        type: string
      title:
        example: Google Home
        type: string
      updated_at:
        example: "2021-10-18T00:49:06.160059334-03:00"
        type: string
      url:
        example: https://www.google.com
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@elga.io
    name: API Support
  description: Micro-serice for managing URLs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://elga.io/terms
  title: URLs API
  version: 0.0.1
paths:
  /urls:
    get:
      consumes:
      - application/json
      description: Get details of all URLs
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Quantity of items
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/app.URL'
            type: array
      summary: Get details of all URLs
      tags:
      - URLs
    post:
      consumes:
      - application/json
      description: Add a new URL
      parameters:
      - description: URL struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/app.PostURL'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Add a new URL
      tags:
      - URLs
  /urls/{id}:
    delete:
      consumes:
      - application/json
      description: Delete URL item
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete URL item
      tags:
      - URLs
    get:
      consumes:
      - application/json
      description: Get URL by ID
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "404":
          description: ""
      summary: Get an URL
      tags:
      - URLs
    patch:
      consumes:
      - application/json
      description: Change URL item
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: string
      - description: URL struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/app.PostURL'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Change URL item
      tags:
      - URLs
    put:
      consumes:
      - application/json
      description: Change or create URL item
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: string
      - description: URL struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/app.PostURL'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Change or create URL item
      tags:
      - URLs
swagger: "2.0"
