CREATE TABLE IF NOT EXISTS users(
	id VARCHAR (30) PRIMARY KEY,
	created_at TIMESTAMP DEFAULT NOW(),
	updated_at TIMESTAMP,
	name VARCHAR (100) NOT NULL,
	role VARCHAR (50) NOT NULL,
	active BOOLEAN DEFAULT true
);
