#
# YOU DON'T NEED THIS MANIFEST FILE IN PRODUCTION ENVIRONMENT.
#
# Its usefull to connect from k8s pod to resource host.
# Like redis, postgresql, etc in docker-compose.
# Check: https://github.com/kubernetes-sigs/kind/issues/1200#issuecomment-1304855791
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dockerhost
  namespace: {{.Values.namespace}}
subsets:
  - addresses:
      - ip: 172.17.0.1 # this is the gateway IP in the "bridge" docker network
---
apiVersion: v1
kind: Service
metadata:
  name: dockerhost
  namespace: {{.Values.namespace}}
spec:
  clusterIP: None
