basePath: /
definitions:
  profile.Profile:
    properties:
      active:
        example: false
        type: boolean
      created_at:
        example: "2021-10-18T00:45:07.818344164-03:00"
        type: string
      email:
        example: oliveira@live.it
        type: string
      id:
        example: eed7df28-5a16-46f0-b5bf-c26071a42ade
        type: string
      last_login:
        example: "2021-10-20T00:50:00.100059334-03:00"
        type: string
      name:
        example: Wellington Oliveira
        type: string
      roles:
        items:
          type: string
        type: array
      tags:
        items:
          type: string
        type: array
      updated_at:
        example: "2021-10-18T00:49:06.160059334-03:00"
        type: string
    type: object
  profile.postProfileRequest:
    properties:
      profile:
        $ref: '#/definitions/profile.Profile'
    type: object
  pwd.signInPwdRequest:
    properties:
      created_at:
        example: "2021-10-18T00:45:07.818344164-03:00"
        type: string
      email:
        example: oliveira@live.it
        type: string
      id:
        example: eed7df28-5a16-46f0-b5bf-c26071a42ade
        type: string
      last_login:
        example: "2021-10-20T00:50:00.100059334-03:00"
        type: string
      password:
        type: string
      updated_at:
        example: "2021-10-18T00:49:06.160059334-03:00"
        type: string
    type: object
  url.URL:
    properties:
      active:
        example: false
        type: boolean
      created_at:
        example: "2021-10-18T00:45:07.818344164-03:00"
        type: string
      id:
        example: eed7df28-5a16-46f0-b5bf-c26071a42ade
        type: string
      keyword:
        example: google
        type: string
      owner_id:
        example: 5ca04a43-ff3c-4154-a8ad-02e2e906a847
        type: string
      title:
        example: Google Home
        type: string
      updated_at:
        example: "2021-10-18T00:49:06.160059334-03:00"
        type: string
      url:
        example: https://www.google.com
        type: string
    type: object
  url.postURLRequest:
    properties:
      url:
        $ref: '#/definitions/url.URL'
    type: object
host: localhost:8080
info:
  contact:
    email: support@elga.io
    name: API Support
  description: Micro-serice for managing URL
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://elga.io/terms
  title: URL API
  version: 0.0.1
paths:
  /auth/pwd/v1/signin:
    post:
      consumes:
      - application/json
      description: Authenticate the user
      parameters:
      - description: Pwd struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pwd.signInPwdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Authenticate the user
      tags:
      - Pwd
  /auth/pwd/v1/signup:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Pwd struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pwd.signInPwdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Create a new user
      tags:
      - Pwd
  /profile/v1/profiles:
    get:
      consumes:
      - application/json
      description: Get details of all Profiles
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Quantity of items
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/profile.Profile'
            type: array
      summary: Get details of all Profiles
      tags:
      - Profile
    post:
      consumes:
      - application/json
      description: Add a new Profile
      parameters:
      - description: Profile struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/profile.postProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Add a new Profile
      tags:
      - Profile
  /profile/v1/profiles/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Profile item
      parameters:
      - description: Profile ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete Profile item
      tags:
      - Profile
    get:
      consumes:
      - application/json
      description: Get Profile by ID
      parameters:
      - description: Profile ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "404":
          description: ""
      summary: Get an Profile
      tags:
      - Profile
    patch:
      consumes:
      - application/json
      description: Change Profile item
      parameters:
      - description: Profile ID
        in: path
        name: id
        required: true
        type: string
      - description: Profile struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/profile.postProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Change Profile item
      tags:
      - Profile
    put:
      consumes:
      - application/json
      description: Change or create Profile item
      parameters:
      - description: Profile ID
        in: path
        name: id
        required: true
        type: string
      - description: Profile struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/profile.postProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Change or create Profile item
      tags:
      - Profile
  /url/v1/urls:
    get:
      consumes:
      - application/json
      description: Get details of all URLs
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Quantity of items
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/url.URL'
            type: array
      summary: Get details of all URLs
      tags:
      - URL
    post:
      consumes:
      - application/json
      description: Add a new URL
      parameters:
      - description: URL struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/url.postURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Add a new URL
      tags:
      - URL
  /url/v1/urls/{id}:
    delete:
      consumes:
      - application/json
      description: Delete URL item
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete URL item
      tags:
      - URL
    get:
      consumes:
      - application/json
      description: Get URL by ID
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "404":
          description: ""
      summary: Get an URL
      tags:
      - URL
    patch:
      consumes:
      - application/json
      description: Change URL item
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: string
      - description: URL struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/url.postURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Change URL item
      tags:
      - URL
    put:
      consumes:
      - application/json
      description: Change or create URL item
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: string
      - description: URL struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/url.postURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Change or create URL item
      tags:
      - URL
swagger: "2.0"
