direction: right

API: Corgi
Cache: Redis
Database: PostgreSQL

API.shape: circle

Cache.shape: cylinder
Cache.tooltip: "Used to cache data and count of redirect clicks."

Database.shape: cylinder
Database.tooltip: "Used to persist data."

API -> Cache: {
  style.animated: true
}

API -> Database: {
  style.animated: true
}
