app:
  log_level: debug
  secret_key: 12345
  admin_password: 12345
  user_password: 12345

auth:
  google:
    client_id:
    client_secret:

server:
  http_port: 8081
  grpc_port: 8082
  read_timeout: 60
  write_timeout: 60

database:
  host: localhost
  port: 26257
  user:
  password:
  database: corgi

cache:
  host: localhost
  port: 6379
  user:
  password:
  database: 1
  max_idle: 30
  max_active: 30
  idle_timeout: 200

search:
  host: localhost
  port: 9200
  user:
  password:
