app:
  log_level: info
  secret_key: CHANGE_FOR_SOMETHING_MORE_SECURITY
  redirect_url: http://127.0.0.1:8081

auth:
  google:
    client_id: 180551609644-qf392m12gr5p68eor6m2jamvjup42ul7.apps.googleusercontent.com
    client_secret: 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

  facebook:
    client_id:
    client_secret:

server:
  http_port: 8081
  grpc_port: 8082
  read_timeout: 60
  write_timeout: 60

database:
  host: 127.0.0.1
  port: 26257
  user:
  password:
  database: corgi

cache:
  host: 127.0.0.1
  port: 6379
  user:
  password:
  database: 1
  max_idle: 30
  max_active: 30
  idle_timeout: 200
