app:
  log_level: info
  secret_key: CHANGE_FOR_SOMETHING_MORE_SECURITY
  redirect_url: http://127.0.0.1:8081

auth:
  google:
    client_id: 180551609644-qf392m12gr5p68eor6m2jamvjup42ul7.apps.googleusercontent.com
    client_secret: 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

  facebook:
    client_id: 1558055581305469
    client_secret: 6a7fc30fafabdc4247bf3797a63d8bd8

server:
  http_port: 8081
  read_timeout: 60
  write_timeout: 60
