name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      run: make lint
