name: Releaser

on:
  push:
    tags:
      - v*

jobs:
  Releaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build Web UI
        run: make build-web

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
